### ISSUE TITLE
archiver throwing Uncaught TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by maifeeulasad** [maifeeulasad/to-spreadsheet#9]
I get this error on import with `archiver`
Stack-trace:
```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at node_modules/readdir-glob/index.js (index.js:120:1)
    at __require (chunk-J43GMYXM.js?v=5acb6c3b:11:50)
    at node_modules/archiver/lib/core.js (core.js:9:12)
    at __require (chunk-J43GMYXM.js?v=5acb6c3b:11:50)
    at node_modules/archiver/index.js (index.js:8:16)
    at __require (chunk-J43GMYXM.js?v=5acb6c3b:11:50)
    at node_modules/to-spreadsheet/lib/generate-excel.js (generate-excel.js:16:18)
    at __require (chunk-J43GMYXM.js?v=5acb6c3b:11:50)
    at node_modules/to-spreadsheet/lib/index.js (index.js:4:26)
    at __require (chunk-J43GMYXM.js?v=5acb6c3b:11:50)
```

**Comment by maifeeulasad** [comment]
Resolved by: 1a4e3c63fc8e2a6aa8ff529968f0c437f54649d7

Related issue: https://github.com/maifeeulasad/to-spreadsheet/issues/10
